import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
 createWorkspaceMirrorScheduler, markdownFence, renderWorkspaceMirror, workspaceMirrorIdentity,
} from '../../dist/src/sync/workspace-mirror.mjs';
import { projectPagesFor } from '../../dist/src/sync/project-pages.mjs';

const pages = projectPagesFor('https://wiki.example', 'Promptr');
const board = {
 version: 1, repoLabel: 'owner/promptr', fetchedAt: '2026-09-07T10:00:00Z', openCount: 4,
 counts: { active: 1, ready: 1, review: 1, blocked: 1, later: 0, unknown: 0 },
 summary: '4 open · 1 active · 1 ready · 1 review · 1 blocked',
 rows: [
  { kind: 'heading', status: 'active', count: 1 },
  { kind: 'issue', issue: { number: 7, title: 'Active task', status: 'active', priority: 'P1', assignee: 'owner', blockers: 0, mapNumber: undefined, labels: [], milestone: '', url: '', updatedAt: '' } },
  { kind: 'issue', issue: { number: 8, title: 'Ready task', status: 'ready', priority: '', assignee: '', blockers: 0, mapNumber: undefined, labels: [], milestone: '', url: '', updatedAt: '' } },
  { kind: 'issue', issue: { number: 9, title: 'Review task', status: 'review', priority: '', assignee: '', blockers: 0, mapNumber: undefined, labels: [], milestone: '', url: '', updatedAt: '' } },
 ],
};
const content = (composer = 'draft') => ({
 project: 'promptr', gitRef: 'main', gitHead: 'abcdef123', gitDirty: false, piStatus: 'w8:p2 idle',
 queue: [{ text: 'plain' }, { text: 'contains ``` and ```` fences\nexact tail' }], composer, board,
});

function clockHarness(write) {
 let now = 1_700_000_000_000;
 let sequence = 0;
 const timers = [];
 const statuses = [];
 const client = { async readDocument() { return null; }, async createPage() { return 'exists'; }, writeMarkdown: write };
 const scheduler = createWorkspaceMirrorScheduler({
  now: () => now,
  setTimer: (callback, delay) => { const timer = { at: now + delay, callback, active: true, sequence: sequence++ }; timers.push(timer); return timer; },
  clearTimer: (timer) => { timer.active = false; },
  onStatus: (status) => statuses.push(status),
 });
 const advance = async (ms) => {
  const target = now + ms;
  for (;;) {
   const next = timers.filter((t) => t.active && t.at <= target).sort((a, b) => a.at - b.at || a.sequence - b.sequence)[0];
   if (!next) break;
   next.active = false; now = next.at; next.callback();
   await Promise.resolve(); await Promise.resolve();
  }
  now = target; await Promise.resolve(); await Promise.resolve();
 };
 return { scheduler, client, statuses, advance, now: () => now };
}
const observation = (h, value = content(), selectedPages = pages) => ({ pages: selectedPages, client: h.client, content: value });

test('renderer uses safe fences, exact sections, and only active/ready workboard rows', () => {
 const stamp = '2026-09-07T12:34:56.000Z';
 const out = renderWorkspaceMirror(content(), stamp);
 assert.equal(markdownFence('a ```` b'), '`````');
 assert.match(out, /^# promptr workspace\n\nProject: promptr\nGit: main @abcdef123\nPi: w8:p2 idle\nUpdated: /);
 assert.ok(out.includes('> Machine-written by Promptr. Edits to this page are overwritten; history lives on the prompt-log page.'));
 assert.ok(out.includes('## Queue\n\n### 1.\n\n```\nplain\n```\n\n### 2.'));
 assert.ok(out.includes('`````\ncontains ``` and ```` fences\nexact tail\n`````'));
 assert.ok(out.includes('## Composer\n\n```\ndraft\n```'));
 assert.ok(out.includes(board.summary));
 assert.ok(out.includes('- #7 [active] Active task'));
 assert.ok(out.includes('- #8 [ready] Ready task'));
 assert.ok(!out.includes('Review task'));
});

test('identity excludes timestamp/board age but includes meaningful workspace content', () => {
 const a = content();
 const b = { ...content(), board: { ...board, fetchedAt: '2030-01-01T00:00:00Z' } };
 assert.equal(workspaceMirrorIdentity(a), workspaceMirrorIdentity(b));
 assert.notEqual(workspaceMirrorIdentity(a), workspaceMirrorIdentity(content('changed')));
 const first = renderWorkspaceMirror(a, '2026-01-01T00:00:00Z');
 const second = renderWorkspaceMirror(a, '2026-01-02T00:00:00Z');
 assert.notEqual(first, second, 'timestamp is generated by the actual attempt, not identity');
});

test('real changes reset 10s debounce; unchanged observations and navigation-like no-ops do not', async () => {
 const writes = [];
 const h = clockHarness(async (...args) => { writes.push(args); });
 h.scheduler.observe(observation(h));
 await h.advance(9_000);
 h.scheduler.observe(observation(h));
 await h.advance(1_000);
 assert.equal(writes.length, 1, 'same observation did not reset the original debounce');
 h.scheduler.observe(observation(h, content('changed')));
 await h.advance(9_000);
 h.scheduler.observe(observation(h, content('latest')));
 await h.advance(9_999);
 assert.equal(writes.length, 1);
 await h.advance(11_001);
 assert.equal(writes.length, 2, 'latest change waits for quiet and the 30s attempt throttle');
 assert.ok(writes[1][1].includes('\nlatest\n'));
 assert.ok(writes.every((call) => call[0] === pages.workspace && call[2] === 'replace'));
});

test('clean to dirty is a real change that schedules and renders the canonical star suffix', async () => {
 const writes = [];
 const h = clockHarness(async (...args) => { writes.push(args); });
 h.scheduler.observe(observation(h));
 await h.advance(10_000);
 assert.ok(writes[0][1].includes('Git: main @abcdef123\n'));
 assert.ok(!writes[0][1].includes('Git: main @abcdef123*'));
 const dirty = { ...content(), gitDirty: true };
 assert.notEqual(workspaceMirrorIdentity(content()), workspaceMirrorIdentity(dirty));
 assert.ok(renderWorkspaceMirror(dirty, '2026-09-07T12:34:56.000Z').includes('Git: main @abcdef123*\n'));
 h.scheduler.observe(observation(h, dirty));
 await h.advance(30_000);
 assert.equal(writes.length, 2);
 assert.ok(writes[1][1].includes('Git: main @abcdef123*\n'));
});

test('failure remains pending through an unchanged/reachability observation; next content change retries', async () => {
 let fail = true; const writes = [];
 const h = clockHarness(async (...args) => { writes.push(args); if (fail) throw new Error('offline'); });
 h.scheduler.observe(observation(h));
 await h.advance(10_000);
 assert.equal(writes.length, 1); assert.equal(h.scheduler.current(), 'pending');
 h.scheduler.observe(observation(h));
 await h.advance(60_000);
 assert.equal(writes.length, 1, 'no endless retry and healthy poll/no-op cannot clear pending');
 fail = false;
 h.scheduler.observe(observation(h, content('next change')));
 await h.advance(10_000);
 assert.equal(writes.length, 2); assert.equal(h.scheduler.current(), 'synced');
});

test('in-flight write retains a copied latest snapshot and never overlaps', async () => {
 const writes = []; let release;
 const gate = new Promise((resolve) => { release = resolve; });
 let active = 0; let maxActive = 0;
 const h = clockHarness(async (...args) => { writes.push(args); active++; maxActive = Math.max(maxActive, active); if (writes.length === 1) await gate; active--; });
 const mutable = content('first');
 h.scheduler.observe(observation(h, mutable));
 await h.advance(10_000);
 mutable.queue[0].text = 'mutated after observation';
 h.scheduler.observe(observation(h, content('latest while flying')));
 await h.advance(40_000);
 assert.equal(writes.length, 1); assert.ok(writes[0][1].includes('\nplain\n')); assert.ok(!writes[0][1].includes('mutated after'));
 release(); await Promise.resolve(); await Promise.resolve();
 await h.advance(0);
 assert.equal(writes.length, 2); assert.ok(writes[1][1].includes('latest while flying')); assert.equal(maxActive, 1);
});

test('binding changes pin old writes, invalidate completion/cache, and unbound/demo never writes', async () => {
 const writes = []; let release;
 const gate = new Promise((resolve) => { release = resolve; });
 const h = clockHarness(async (...args) => { writes.push(args); if (writes.length === 1) await gate; });
 h.scheduler.observe(undefined);
 await h.advance(30_000); assert.equal(writes.length, 0);
 h.scheduler.observe(observation(h)); await h.advance(10_000);
 const other = projectPagesFor('https://other.example', 'Other', 'projects/other/brief');
 h.scheduler.observe(observation(h, content('other target'), other));
 release(); await Promise.resolve(); await Promise.resolve();
 await h.advance(30_000);
 assert.equal(writes.length, 2);
 assert.equal(writes[0][0], pages.workspace); assert.equal(writes[1][0], other.workspace);
 assert.ok(writes[1][1].includes('other target'));
 h.scheduler.observe(undefined); await h.advance(60_000);
 assert.equal(writes.length, 2); assert.equal(h.scheduler.current(), 'unbound');
});
