import assert from "node:assert/strict";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
// @ts-expect-error plain ESM helper without types
import { currentSection, parseRemote, replaceSection, run } from "../../skills/slopscore-pr/scripts/pr-body.mjs";

/** The skill: one source, a byte-identical plugin copy, confirmations in the text, and a PR body helper that never pushes. */

const root = fileURLToPath(new URL("../../", import.meta.url));
const source = join(root, "skills", "slopscore-pr");
const copy = join(root, "claude-code", "skills", "slopscore-pr");

function files(dir: string, prefix = ""): string[] {
	return readdirSync(dir).flatMap((name) => {
		const path = join(dir, name);
		return statSync(path).isDirectory() ? files(path, `${prefix}${name}/`) : [`${prefix}${name}`];
	}).sort();
}

test("the plugin skill copy is byte-identical to the root skill", () => {
	const names = files(source);
	assert.ok(names.includes("SKILL.md") && names.includes("scripts/pr-body.mjs"));
	assert.deepEqual(files(copy), names);
	for (const name of names) assert.ok(readFileSync(join(copy, name)).equals(readFileSync(join(source, name))), name);
});

test("the skill text asks before the rebase and before the PR edit, and never contains a push command", () => {
	const text = readFileSync(join(source, "SKILL.md"), "utf8");
	const helper = readFileSync(join(source, "scripts", "pr-body.mjs"), "utf8");
	assert.match(text, /^name: slopscore-pr$/m);
	assert.match(text, /Rebase the branch and add these trailers\?/);
	assert.match(text, /Update the PR body\?/);
	assert.match(text, /Stop here unless the user says yes/);
	assert.match(text, /--add-trailers/);
	assert.match(text, /GITEA_TOKEN/);
	assert.match(text, /<skill directory>\/scripts\/pr-body\.mjs/);
	assert.match(text, /paste/i);
	assert.doesNotMatch(text, /git push/);
	assert.doesNotMatch(helper, /git push|\["push"|"push",/);
});

const block = "## slopscore\n\n| Scope | Sessions |\n| --- | ---: |\n| branch feature/x vs main, 1 commits, 1 days | 2 |\n\n_Generated by slopscore-pr on 2026-09-19._";
const templateBody = "## Summary\n\nDoes the thing. Closes #12.\n\n## slopscore\n\n<!-- Run `slopscore pr` and paste the block here. -->\n\n## Checklist\n\n- [x] tests\n";

test("replaceSection replaces only the slopscore section and appends when it is missing", () => {
	const replaced = replaceSection(templateBody, block);
	assert.equal(replaced, `## Summary\n\nDoes the thing. Closes #12.\n\n${block}\n\n## Checklist\n\n- [x] tests\n`);
	assert.ok(!replaced.includes("paste the block here"));
	assert.equal(replaceSection("## Summary\n\nJust text.\n", block), `## Summary\n\nJust text.\n\n${block}\n`);
	assert.equal(replaceSection("", block), `${block}\n`);
	assert.equal(replaceSection(`Intro\n\n${block}\n`, block.replace("| 2 |", "| 3 |")), `Intro\n\n${block.replace("| 2 |", "| 3 |")}\n`);
});

test("replaceSection stops at an indented h2 or an h1, keeps CRLF bodies and untouched text byte for byte", () => {
	const indented = "## Summary\n\nA  trailing  \n\n## slopscore\n\nold\n\n  ## Checklist\n\n- [ ] x\n\n# Title\n";
	assert.equal(replaceSection(indented, block), `## Summary\n\nA  trailing  \n\n${block}\n\n  ## Checklist\n\n- [ ] x\n\n# Title\n`);
	const h1 = "## slopscore\n\nold\n# Title\ntext\n";
	assert.equal(replaceSection(h1, block), `${block}\n\n# Title\ntext\n`);
	const crlf = "## Summary\r\n\r\nText.\r\n\r\n## slopscore\r\n\r\nold\r\n\r\n## Checklist\r\n\r\n- [x] tests\r\n";
	const replacedCrlf = replaceSection(crlf, block);
	assert.ok(!replacedCrlf.includes("\n\n") || replacedCrlf.includes("\r\n\r\n"));
	assert.ok(replacedCrlf.startsWith("## Summary\r\n\r\nText.\r\n\r\n## slopscore\r\n"));
	assert.ok(replacedCrlf.endsWith("## Checklist\r\n\r\n- [x] tests\r\n"));
	assert.equal(currentSection(crlf), "## slopscore\n\nold");
	assert.equal(currentSection("no section"), undefined);
});

test("run: a copy of the block elsewhere in the body does not stop a stale section from being replaced", async () => {
	const body = `## Summary\n\nQuoted earlier:\n\n\`\`\`markdown\n${block}\n\`\`\`\n\n## slopscore\n\nold block\n`;
	const applied = fakeIo({ number: 9, body, url: "u" });
	const result = await run({ block, branch: "feature/x", remotes, apply: true, ioFor: applied.ioFor });
	assert.match(result.output, /Updated the ## slopscore section of PR #9/);
	assert.equal(applied.updates.length, 1);
	assert.ok(!applied.updates[0].body.includes("old block"));
	assert.ok(applied.updates[0].body.includes("```markdown\n" + block + "\n```"));
	const same = await run({ block, branch: "feature/x", remotes, apply: true, ioFor: fakeIo({ number: 9, body: applied.updates[0].body, url: "u" }).ioFor });
	assert.match(same.output, /already carries this block/);
});

test("parseRemote reads ssh, scp and https remotes", () => {
	assert.deepEqual(parseRemote("git@git.example.com:owner/tenantext.git"), { host: "git.example.com", owner: "owner", repo: "tenantext" });
	assert.deepEqual(parseRemote("https://github.com/example-owner/example-repo"), { host: "github.com", owner: "example-owner", repo: "example-repo" });
	assert.deepEqual(parseRemote("ssh://git@github.com/o/r.git"), { host: "github.com", owner: "o", repo: "r" });
	assert.equal(parseRemote("/local/path"), undefined);
});

type Remote = { host: string; owner: string; repo: string };
function fakeIo(pr: { number: number; body: string; url: string } | undefined, credential = true) {
	const updates: Array<{ number: number; body: string }> = [];
	const io = { credential: () => credential, findPr: async () => pr, updatePr: async (number: number, body: string) => { updates.push({ number, body }); } };
	return { updates, io, ioFor: (_remote: Remote) => io };
}
const remote: Remote = { host: "gitea.example", owner: "o", repo: "r" };
const remotes = [remote];

test("run: template section is replaced, dry run changes nothing, --apply updates the body once", async () => {
	const pr = { number: 7, body: templateBody, url: "https://gitea.example/o/r/pulls/7" };
	const dry = fakeIo(pr);
	const dryResult = await run({ block, branch: "feature/x", remotes, apply: false, ioFor: dry.ioFor });
	assert.equal(dryResult.exitCode, 0);
	assert.match(dryResult.output, /Dry run for PR #7/);
	assert.ok(dryResult.output.includes("## Checklist\n\n- [x] tests"));
	assert.ok(dryResult.output.includes(block));
	assert.deepEqual(dry.updates, []);
	const applied = fakeIo(pr);
	const applyResult = await run({ block, branch: "feature/x", remotes, apply: true, ioFor: applied.ioFor });
	assert.equal(applyResult.exitCode, 0);
	assert.match(applyResult.output, /Updated the ## slopscore section of PR #7/);
	assert.deepEqual(applied.updates, [{ number: 7, body: replaceSection(templateBody, block) }]);
});

test("run: a body without the section gets it appended", async () => {
	const applied = fakeIo({ number: 8, body: "## Summary\n\nText.\n", url: "u" });
	await run({ block, branch: "feature/x", remotes, apply: true, ioFor: applied.ioFor });
	assert.equal(applied.updates[0].body, `## Summary\n\nText.\n\n${block}\n`);
});

test("run: in a fork the PR on upstream is found before origin is tried", async () => {
	const upstream: Remote = { host: "gitea.example", owner: "maintainer", repo: "r" };
	const onUpstream = fakeIo({ number: 3, body: "", url: "up" });
	const onOrigin = fakeIo(undefined);
	const ioFor = (candidate: Remote) => candidate.owner === "maintainer" ? onUpstream.io : onOrigin.io;
	const result = await run({ block, branch: "feature/x", remotes: [upstream, remote], apply: true, ioFor });
	assert.match(result.output, /PR #3/);
	assert.equal(onUpstream.updates.length, 1);
	const originOnly = await run({ block, branch: "feature/x", remotes: [upstream, remote], apply: true, ioFor: () => onOrigin.io });
	assert.equal(originOnly.exitCode, 2);
	assert.match(originOnly.output, /maintainer\/r.*o\/r/s);
});

test("run: no PR, no credential or no remote prints the block and the paste instruction and exits 2", async () => {
	const noPr = await run({ block, branch: "feature/x", remotes, apply: true, ioFor: fakeIo(undefined).ioFor });
	assert.equal(noPr.exitCode, 2);
	assert.match(noPr.output, /No open PR for branch feature\/x on gitea\.example \(o\/r\)\. Paste the block under "## slopscore"/);
	assert.ok(noPr.output.endsWith(block));
	const noToken = await run({ block, branch: "feature/x", remotes, apply: true, ioFor: fakeIo({ number: 1, body: "", url: "u" }, false).ioFor });
	assert.equal(noToken.exitCode, 2);
	assert.match(noToken.output, /GITEA_TOKEN is not set/);
	const noGh = await run({ block, branch: "feature/x", remotes: [{ ...remote, host: "github.com" }], apply: true, ioFor: fakeIo(undefined, false).ioFor });
	assert.match(noGh.output, /gh is not logged in/);
	const noRemote = await run({ block, branch: "feature/x", remotes: [], apply: false, ioFor: undefined });
	assert.equal(noRemote.exitCode, 2);
	const notBlock = await run({ block: "hello", branch: "feature/x", remotes, apply: false, ioFor: fakeIo(undefined).ioFor });
	assert.equal(notBlock.exitCode, 1);
});
